#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustomFast9V)
#pragma config(Motor,  mtr_S1_C1_1,     motorBackRight, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFrontRight, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorBackLeft, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorFrontLeft, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift1,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     harvester,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     lift2,         tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C3_2,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    no,                   tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    ballDrop,             tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    centerLift,           tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_4,    clamp1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    servo7,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_2,    rearTurret,           tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    kickstand,            tServoStandard)
#pragma config(Servo,  srvo_S2_C2_4,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S2_C2_5,    frontTurret,          tServoStandard)
#pragma config(Servo,  srvo_S2_C2_6,    grabberLift2,         tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "JoystickDriver.c"
//#include "drivers/hitechnic-irseeker-v2.h"
#include "../../Common/Ultrasonic-SMUX.h"
#include "../../Common/Touch.h"
#include "../../Common/Movement.h"
#include "../../Common/IMU.h"

bool everPressed = false;

void scoreBall() {
	servo[ballDrop] = 255;
	pause(1.6);
	servo[ballDrop] = 127;
}

void CenterPosition1() {
	turnUltra(0, 90);
	moveDistanceRamp(50, 12);
	binaryTillSenseHeading(80, 270, 30, frontUS);
	PlaySound(soundLowBuzzShort);
	translateDistance(200, 270, 7);
	writeDebugStream("DONE WITH FIRST");
	//binaryTillSense(35, 0, 30, clampUS);
	//repeatedTillSense(35, 0, false, 70, clampUS);
	irTillSensePeak(50);
	//correctToInitialHeading();
}

void CenterPosition2() {
	//turnDistance(-100, 50);
	turnWithGyro(50, -55);
	irTillSensePeak(50);
	//binaryTillSense(30,0,30,clampUS);
}

void CenterPosition3() {
	turnUltra(0, 0);
	turnUltra(1, 0);
	turnWithGyro(50, -90);
	//pause(0.2);
	//incrementalParallel(25, 2, rearUS, frontUS);
	//pause(0.2);
	//translateDistance(100, 90, 16);
	//pause(0.2);
	//	repeatedTillSense(40,0,false, 70, clampUS);
	////binaryTillSense(40,0, 30, clampUS);
	//pause(0.5);
	//moveDistanceRamp(-50, 3);
	//pause(0.2);
}

void CenterToKickstand(int position) {
	translateDistance(100,270,10);
	pause(0.2);
	moveDistance(-100, 25);
	pause(0.2);
	turnDistance(50,110);

	turnUltra(0,0);
	pause(0.2);
	repeatedTillSense(50, 0, false, 90, frontUS);
	pause(0.2);
	if(position == 2)
		tillSense(200, 270, false, 27, frontUS);
	else if(position == 1)
		tillSense(200, 270, false, 22, frontUS);
	else if(position == 3);
		tillSense(200, 270, false, 25, frontUS);

	pause(0.2);
	deployKnocker();
	moveDistance(30, 10);
	moveDistance(100, 30);

}

task ohno() {
	while(true) {
		if(!everPressed && time1[T4] > 25000) {
			StopAllTasks();
		}
	}
}

int CenterGoal() {
	ClearTimer(T4);
	//StartTask(ohno);
	retractKnocker();
	turnUltra(0, 90);
	//moveDistance(50, 20);
	//StartTask(raiseLift);
	moveDistanceRamp(40, 20);
	//translateRTHeading(40);
	//moveDistancePID(20);
	pause(1);
	int position = detectPosition();
	switch(position) {
		case 1:
			sound(1, 0.2);
			CenterPosition1();
			break;
		case 2:
			sound(2, 0.2);
			CenterPosition2();
			break;
		case 3:
			sound(3, 0.2);
			CenterPosition3();
			break;
		default:
			return -1;
	}

	while(!lifted);
	deployClamp();

	readAllSwitches();
	//scoring commences
	ClearTimer(T1);
	int time = 35;
	bool anything_pressed = false;
	while(!sideSwitch || !armSwitch) {
		readAllSwitches();
		//if(!anything_pressed && time100[T1] > time){
		//	translateDistance(50,270,2);
		//	moveDistance(50, 3);
		//	ClearTimer(T1);
		//	anything_pressed = false;
		//};
		if(sideSwitch) { PlaySound(soundLowBuzz); anything_pressed = true; everPressed = true; }
		if(armSwitch) { PlaySound(soundUpwardTones); anything_pressed = true; everPressed = true;}
		if(sideSwitch) {
			move(-20);
		}
		//else  {
		//	translateRT(100, 90);
		//}
		else if (armSwitch)  {
			translateRT(100, 90);
		}
		else {
			if(USreadDist(clampUS)<40){
					move(15);
				}
				else{
					translateRT(100, 90);
				}
		}
	}
	PlaySound(soundBeepBeep);
	translateRT(200, 120);
	scoreBall();
	move(0);
	return position;
}

#ifndef AUTO_COMPETITION
task main() {
	//clearDebugStream();
	//resetArduino();
	//pause(5);
	//PlaySound(soundBeepBeep);
	//irTillSensePeak(50);
	resetArduino();
	pause(5);
	PlaySound(soundBeepBeep);
	//while(true) {
	//	translateDistanceHeading(100, 0, 96);
	//	pause(0.2);
	//	turnWithGyro(50, 90);
	//	pause(0.2);
	//}
	int position = CenterGoal();
	//CenterToKickstand(position);
	//int direction = 1;
	//moveDistance(direction*-100,20);
	//playSound(soundBeepBeep);
	//irTillSensePeak(direction*50);
}
#endif
