#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S3,     rearUltra,      sensorSONAR)
#pragma config(Sensor, S4,     frontUltra,     sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorFrontLeft, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBackLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorFrontRight, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorBackRight, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     harvester,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    lift1,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    lift2,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    frontTurret,          tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    rearTurret,           tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    grabber,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-irseeker-v2.h"
#include "../../Common/Movement.h"
#define robotLength 12.0

void sound(int number, float pausetime){
	int i;
	for(i=0; i<number;i++){
		playsound(soundBlip);
		pause(pausetime);
	}
}

void Position1() {
	sound(1,0);
	turnUltra(0, 0);
	turnUltra(1, 0);
	pause(0.1);
	moveDistance(-50, 8);
	turnDistance(-50, 90);
	pause(0.1);
	tillSense(-50, 0, false, 90, ultra1);
	pause(0.5);

	parallel(30, 0, ultra0, ultra1);
	pause(0.5);
	tillSense(-50, 0, true, 90, ultra0);
	tillSense(-50, 90, false, 12, ultra0);
 	moveDistance(100, 12);
}

void Position2() {
	sound(2,0.2);
	turnUltra(0, 0);
	turnUltra(1, 0);
	pause(0.1);
	turnDistance(-50, 140);
	translateDistance(50, 90, 5);
	pause(0.1);
	tillSense(50, 0, false, 90, ultra1);
	moveDistance(50, 3);
	tillSense(-50, 90, false, 3, ultra0);
	moveDistance(50, 3);
	//pause(0.1);
	//parallel(30, 0, ultra0, ultra1);
	//pause(0.1);
	//tillSense(-50, 90, false, 30, ultra0);
	//tillSense(-50, 0, true, 90, ultra1);
	//pause(0.1);
	//turnDistance(50, 90);
	//turnUltra(1, 0);
	//pause(0.1);
	//tillSense(-50, 0, false, 25, ultra0);
	//tillSense(-50, 0, true, 30, ultra0);
}

void Position3() {
	sound(3,0.2);
	turnUltra(0, 90);
	turnDistance(50, 180);
	translateDistance(50, 90, 8);
	tillSense(50, 0, false, 90, ultra0);
}

int detectPosition(){
		float avg = 0;
	const int READINGS = 30;
	int READINGSARR[30];
	for(int i=0; i<READINGS; i++) {
		READINGSARR[i]=SensorValue[ultra0];
		avg += SensorValue[ultra0];
		wait1Msec(20):
	}
	avg /= READINGS;
	float filtered_avg = 0;
	int threshold = 30;
	for(int i=0; i<READINGS; i++){
		if(abs(avg - READINGSARR[i])<threshold){
			filtered_avg += READINGSARR[i];
		}
	}
	filtered_avg = filtered_avg/30;

	if(filtered_avg < 60)
		return 3;
	else if(100 > filtered_avg && filtered_avg > 65)
		return 1;
	else
		return 2;
}

void Kickstand() {
	servo[grabber] = 127;
	turnUltra(0, 90);
	moveDistance(-50, 20);
	pause(0.3);
	int position = detectPosition();
	switch(position) {
		case 1:
			Position1();
			break;
		case 2:
			Position2();
			break;
		case 3:
			Position3();
			break;
		default:
			return;
	}
}

#ifndef AUTO_COMPETITION
task main() {
	Kickstand();
}
#endif
