#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S3,     HTSMUX,         sensorLowSpeed)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustomFast9V)
#pragma config(Motor,  mtr_S1_C1_1,     motorBackRight, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFrontRight, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorBackLeft, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorFrontLeft, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     harvester,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     motorj,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_2,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    lift1,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_2,    lift2,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    frontTurret,          tServoStandard)
#pragma config(Servo,  srvo_S2_C2_2,    rearTurret,           tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoStandard)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../../Common/Ultrasonic-SMUX.h"
#include "../../Common/IMU.h"
#include "../../Common/Movement.h"

#define robotLength 12.0

const tMUXSensor frontUS = msensor_S3_1;
const tMUXSensor rearUS = msensor_S3_2;

void sound(int number, float pausetime){
	int i;
	for(i=0; i<number;i++){
		playsound(soundBlip);
		pause(pausetime);
	}
}

void Position1() {
	sound(1,0);
	turnUltra(0, 0);
	turnUltra(1, 0);
	pause(0.1);
	moveDistance(-50, 8);
	turnDistance(-50, 90);
	pause(0.1);
	tillSense(-200, 0, false, 90, rearUS);
	pause(0.5);

	parallel(30, 0, frontUS, rearUS);
	pause(0.5);
	tillSense(-50, 0, true, 90, frontUS);
	tillSense(-200, 90, false, 12, frontUS);
 	moveDistance(100, 12);
}

void performTheCharge() {
	tillSense(200, 0, false, 30, frontUS);
	if(USreadDist(frontUS) > 7) {
		pause(0.1);
		moveDistance(-100, 10);
		pause(0.1);
		translateDistance(-200, 90, 12);
		pause(0.1);
		performTheCharge();
	}
	else {
		translateDistance(-200, 90, 7);
	}
}

void Position2() {
	sound(2,0.2);
	turnUltra(0, 0);
	turnUltra(1, 0);
	pause(0.1);
	turnDistance(50, 45);
	translateDistance(-200, 90, 20);
	pause(0.1);
	performTheCharge();
	moveDistance(100, 30);
	//tillSense(-200, 90, false, 5, frontUS);
	//pause(0.1);
	//parallel(30, 0, ultra0, ultra1);
	//pause(0.1);
	//tillSense(-50, 90, false, 30, ultra0);
	//tillSense(-50, 0, true, 90, ultra1);
	//pause(0.1);
	//turnDistance(50, 90);
	//turnUltra(1, 0);
	//pause(0.1);
	//tillSense(-50, 0, false, 25, ultra0);
	//tillSense(-50, 0, true, 30, ultra0);
}

void Position3() {
	sound(3,0.2);
	turnUltra(0, 0);
	translateDistance(200, 90, 20);
	tillSense(50, 0, false, 90, frontUS);
	tillSense(200, 90, false, 10, frontUS);
}

int detectPosition(){
	float avg = 0;
	const int READINGS = 30;
	int READINGSARR[30];
	for(int i=0; i<READINGS; i++) {
		READINGSARR[i]=USreadDist(rearUS);
		avg += USreadDist(rearUS);
		wait1Msec(20):
	}
	avg /= READINGS;
	float filtered_avg = 0;
	int threshold = 30;
	for(int i=0; i<READINGS; i++){
		if(abs(avg - READINGSARR[i])<threshold){
			filtered_avg += READINGSARR[i];
		}
	}
	filtered_avg = filtered_avg/30;

	if(filtered_avg < 60)
		return 3;
	else if(100 > filtered_avg && filtered_avg > 65)
		return 1;
	else
		return 2;
}

void Kickstand() {
	turnUltra(0, 90);
	moveDistance(50, 20);
	pause(0.3);
	resetArduino();
	int position = detectPosition();
	PlaySound(soundBeepBeep);
	switch(position) {
		case 1:
			nxtDisplayCenteredTextLine(2, "POSITION 1");
			Position1();
			break;
		case 2:
			nxtDisplayCenteredTextLine(2, "POSITION 2");
			Position2();
			break;
		case 3:
			nxtDisplayCenteredTextLine(2, "POSITION 3");
			Position3();
			break;
		default:
			return;
	}
}

#ifndef AUTO_COMPETITION
task main() {
	resetArduino();
	pause(5);
	turnWithGyro(50, 90);
	//Kickstand();
}
#endif
