#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     backUltra,      sensorSONAR)
#pragma config(Sensor, S3,     frontUltra,     sensorSONAR)
#pragma config(Sensor, S4,     color,          sensorCOLORFULL)
#pragma config(Motor,  mtr_S1_C1_1,     liftMotors,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotors,    tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightMotors,   tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     spinner,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     liftStageOne,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     liftStageTwo,  tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    rearUltraServo,       tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    bucketTilt,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    bucketGate,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    grabber,              tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-irseeker-v2.h"
#include "../../Common/basicMovement.c"
#define robotLength 12.0

void grabTube(){
	servo[grabber] = 255;
	pause(1.2);
	servo[grabber] = 127;
}
void releaseTube(){
	servo[grabber] = 0;
	pause(1);
	servo[grabber] = 127;
}
void tillBack(int speed,bool sees){
	//Takes in a speed and a sees boolean.
	//This ends when the back ultra sonic either sees something or doesn't
	//see something depending on the sees boolean
	move(speed);
	if(sees){
		while(SensorValue[backUltra] >225){};
	}
	else{
		while(SensorValue[backUltra] <225){};
	}
	move(0);
}
void tillFront(int speed, bool sees){
	//Takes in a speed and a sees boolean.
	//This ends when the back ultra sonic either sees something or doesn't
	//see something depending on the sees boolean
	move(speed);
	if(sees){
		while(SensorValue[backUltra] >225){};
	}
	else{
		while(SensorValue[backUltra] <225){};
	}
	move(0);
}
bool tooClose(int threshold){
	//Sees if it is too close to drive in and get closer
	return ((SensorValue[frontUltra] + SensorValue[backUltra])/2 < threshold);
}
/*
void parallel(int speed){
	//Parrallells the robot. Threshold is the closeness of the sensors
	while(SensorValue[frontUltra] > SensorValue[backUltra]){
		turn(speed);
	}

	while(SensorValue[backUltra] > SensorValue[frontUltra]){
		turn(-speed);
	}
}
*/

void parallel(int speed){
	//Parrallells the robot. Threshold is the closeness of the sensors
	while(abs(SensorValue[frontUltra] - SensorValue[backUltra]) > 0) {
		if(SensorValue[frontUltra] > SensorValue[backUltra]){
			turn(-speed);
		}
		else {
			turn(speed);
		}
	}
	move(0);
}

void turnUltra(int angle) {
	int ZERO = 189;
	int scaled = angle * 255.0/180.0;

	servo[rearUltraServo] = ZERO - scaled;

	pause(0.4);
}

void tillBackWithFilter(int speed,bool sees){
	//Takes in a speed and a sees boolean.
	//This ends when the back ultra sonic either sees something or doesn't
	//see something depending on the sees boolean
	move(speed);
	if(sees){
		while(true){
			while(SensorValue[backUltra] > 225){};
			int dist = SensorValue[backUltra];
			move(0);
			turnUltra(-1*atan2(45,dist)-10);
			pause(1);
			move(speed);
			if(SensorValue[backUltra]>225){
				turnUltra(0);
				while(SensorValue[backUltra] < 225){};
			}
			else{
				turnUltra(0);
				break;
			}

		}
	}
	else{
		while(SensorValue[backUltra] <225){};
	}
	move(0);
}

void Simple(){
	servo[bucketGate] = 0;
	releaseTube();
	turnUltra(0);
	moveDistance(-100, 70);

	turnDistance(100, 100);
	moveDistance(-100, 70);
}

#ifndef AUTO_COMPETITION
task main() {
	Simple();
}
#endif
