#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S2, HTMotor,  HTServo,  HTServo,  none)
#pragma config(Sensor, S3,     ultra1,         sensorSONAR)
#pragma config(Sensor, S4,     ultra0,         sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     motorFrontLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBackLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     harvester,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     conveyor,       tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorBackRight, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     motorFrontRight, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Servo,  srvo_S2_C2_1,    grabber,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_2,    utlraServo0,          tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    ultraServo1,          tServoStandard)
#pragma config(Servo,  srvo_S2_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_1,    lift1,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C3_2,    lift2,                tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C3_3,    servo9,               tServoNone)
#pragma config(Servo,  srvo_S2_C3_4,    servo10,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_5,    servo11,              tServoNone)
#pragma config(Servo,  srvo_S2_C3_6,    servo12,              tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "drivers/hitechnic-irseeker-v2.h"
#include "../../Common/Movement.h"
#define robotLength 12.0

task main()
{
	//turnUltra(0, -20);
	//turnUltra(1,-20);
	while(true){
		nxtDisplayCenteredTextLine(1,"front: %d", SensorValue[ultra1]);
		nxtDisplayCenteredTextLine(2,"back: %d", SensorValue[ultra0]);
		wait1Msec(5);
		//		nxtDisplayCenteredTextLine(1,"front: %d", SensorValue[ultra1]);
		//nxtDisplayCenteredTextLine(2,"back: %d", SensorValue[ultra0]);
	}


}
