import glob

FILES = glob.glob("*/*.c") # matches all .c files that are children of current directory
CONFIG = "config.h"
DELIMETER = "//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//\n"

for path in FILES:
	originalFile = []
	configFile = []
	f = open(path, 'r')
	for line in f:
		if line == DELIMETER: 
			originalFile = [] #reached the end of config, start over again
		else:
			originalFile.append(line)
	f.close()

	f = open(CONFIG, 'r')
	for line in f:
		if not (line == DELIMETER.strip('\n') or line == DELIMETER):
			configFile.append(line)
		else:
			print "delimeter"
	f.close()

	f = open(path, 'w')
	for line in configFile:
		f.write(line)
	f.write(DELIMETER)
	for line in originalFile:
		f.write(line)
	f.close()