find -type f -name "*.c" -exec bash -c 'sed "0,%^\/\/\*\!\!Code automatically generated by \'ROBOTC\' configuration wizard               \!\!\*\/\/$%d"' \;

a=$(cat config.h)

find -name "*.c" -type f -print0 | xargs -0 sed -i -e '0,/Code automatically generated by \'ROBOTC\' configuration wizard/Ic '

sed -i.bkp -e "0,/code automatically generated/{c$(cat config.h)" -e "d}"
# ^^ current best attempt
