#pragma config(Sensor, S1,     light,          sensorLightInactive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		nxtDisplayCenteredTextLine(2, "Light value: %d", SensorValue[light]);
		wait1Msec(5);
	}
}
