#pragma config(Sensor, S1,     touch,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		if(SensorValue[touch] == 1) {
			nxtDisplayCenteredTextLine(2, "Pressed!");
		}
		if(SensorValue[touch] == 0) {
			nxtDisplayCenteredTextLine(2, "Not pressed.");
		}
		wait1Msec(5);
	}
}
