#pragma config(Sensor, S1,     ultrasonic,       sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true) {
		//Ultrasonic only works properly between 25 and 100 cm.
		if(SensorValue[ultrasonic] < 20)
			nxtDisplayCenteredTextLine(2, "Too close!");
		else if(SensorValue[ultrasonic] > 120)
			nxtDisplayCenteredTextLine(2, "Too far! (or error)");
		else
			nxtDisplayCenteredTextLine(2, "Good.");

		nxtDisplayCenteredTextLine(3, "Distance: %d cm", SensorValue[ultrasonic]);
	}
}
