#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     liftMotors,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     leftMotors,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     rightMotors,   tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     scoop,         tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     tilt,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     nomotor,       tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    grabber,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    bucketGate,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_3,    scoopGate,            tServoStandard)
#pragma config(Servo,  srvo_S1_C3_4,    bucketLift,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void init() {

}
int bucketliftval = 255;
task arm() {
	while(true) {
			getJoystickSettings(joystick);
			if(joy1Btn(6)){
				motor[scoop] = -40;
			}
			else if(joy1Btn(8 )){
				motor[scoop] = 40;
			}
			else{
				motor[scoop] = 0;
			}
			if(joy2Btn(1)){
				servo[bucketGate] = 230;
			}
			else if(joy2Btn(3)){
				servo[bucketGate] = 122;
			}
			if(joy2Btn(2)){
				bucketliftval++;
				if(bucketliftval > 255)
					bucketliftval = 255;
			}
			else if(joy2Btn(4)){
				bucketliftval--;
				if (bucketliftval<0)
					bucketliftval = 0;
			}
			if(joy1Btn(2)){
				servo[scoopGate] = 122;
			}
			else if(joy1Btn(4)){
				servo[scoopGate] = 0 ;
			}

			if(joy2Btn(5)){
				motor[tilt] = 100;
			}
			else if(joy2Btn(7)){
				motor[tilt] = -100;
			}
			else{
				motor[tilt] = 0;
			}

			if(joy2Btn(6)){
				motor[liftMotors] = -100;
			}
			else if(joy2Btn(8)){
				motor[liftMotors] = 100;
			}
			else{
				motor[liftMotors] = 0;
			}

			if(joy1Btn(5)){
				servo[grabber] = 20;
			}
			else if(joy1Btn(7)){
				servo[grabber] = 140;
			}
			servo[bucketLift] = bucketliftval;
	}
}

task main()
{
	waitForStart();
	StartTask(arm);
	while(true) {
		getJoystickSettings(joystick);

		if(abs(joystick.joy1_y1) < 10)
			joystick.joy1_y1 = 0;
		if(abs(joystick.joy1_y2) < 10)
			joystick.joy1_y2 = 0;

		motor[leftMotors] = joystick.joy1_y1 * -100.0/128;
		motor[rightMotors] = joystick.joy1_y2 * -100.0/128;
	}
}
