#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     motorFrontLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorBackLeft, tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorBackRight, tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorFrontRight, tmotorTetrix, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Common/Movement.h"

task main() {
	resetEncoders();

	wait1Msec(5);
	translateRT(60, 30);
	wait1Msec(1000);
	motor[motorFrontLeft] = 0;
	motor[motorFrontRight] = 0;
	motor[motorBackLeft] = 0;
	motor[motorBackRight] = 0;
	while(true) {
		nxtDisplayCenteredTextLine(1, "FL: %d", nMotorEncoder[motorFrontLeft]);
		nxtDisplayCenteredTextLine(2, "FR: %d", nMotorEncoder[motorFrontRight]);
		nxtDisplayCenteredTextLine(3, "BL: %d", nMotorEncoder[motorBackLeft]);
		nxtDisplayCenteredTextLine(4, "BR: %d", nMotorEncoder[motorBackRight]);
		wait1Msec(5);
	}

}
