#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTServo,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S3,     HTSMUX,         sensorI2CCustom)
#pragma config(Sensor, S4,     HTSPB,          sensorI2CCustomFast9V)
#pragma config(Motor,  mtr_S1_C1_1,     motorBackRight, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorFrontRight, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     motorBackLeft, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     motorFrontLeft, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     lift1,         tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     harvester,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C3_1,     lift2,         tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S2_C3_2,     conveyor,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    ballRamp,             tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    egLift,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    egRelease,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    clamp2,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C1_5,    frontTurret,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S2_C2_1,    clamp1,               tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_2,    rearTurret,           tServoStandard)
#pragma config(Servo,  srvo_S2_C2_3,    kickstand,            tServoStandard)
#pragma config(Servo,  srvo_S2_C2_4,    grabberLift1,         tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_5,    grabber,              tServoContinuousRotation)
#pragma config(Servo,  srvo_S2_C2_6,    grabberLift2,         tServoContinuousRotation)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//#include "JoystickDriver.c"
//#include "drivers/hitechnic-irseeker-v2.h"
#include "JoystickDriver.c"
#include "../Common/Ultrasonic-SMUX.h"
#include "../Common/Touch.h"
#include "../Common/Movement.h"
#include "../Common/IMU.h"

bool everPressed = false;

void scoreBall() {
	servo[egLift] = 0;
	servo[ballRamp] = 60;
	pause(0.4);
	servo[egRelease] = 0;
	pause(2);
	servo[egRelease] = 127;
}

void CenterPosition1() {
	turnUltra(0, 90);
	moveDistanceRamp(50, 12);
	binaryTillSenseHeading(120, 270, 30, frontUS);
	PlaySound(soundLowBuzzShort);
	translateDistance(200, 270, 7);
	writeDebugStream("DONE WITH FIRST");
	turnUltra(0,0);
	pause(0.2);
	irTillSensePeak(30);
	playSound(soundLowBuzz);
	turnWithGyro(30,0);
}

void CenterPosition2() {
	turnWithGyro(70, -45);
	translateDistanceHeading(100, 90, 4);
	turnUltra(0, 0);
	pause(0.2);
	irTillSensePeak(30);
		playSound(soundLowBuzz);
	turnWithGyro(30,0);
}

void CenterPosition3() {
	turnUltra(0, 0);
	turnUltra(1, 0);
	turnWithGyro(50, -90);
}

void CenterToKickstand(int position) {
	translateDistance(100,270,10);
	pause(0.2);
	moveDistance(-100, 30);
	pause(0.2);
	turnWithGyro(100, 90);

	turnUltra(0,0);
	pause(0.2);
	repeatedTillSense(50, 0, false, 90, rearUS);
	pause(0.2);
	if(position == 2)
		tillSense(200, 270, false, 28, rearUS);
	else if(position == 1)
		tillSense(200, 270, false, 27, rearUS);
	else if(position == 3);
		tillSense(200, 270, false, 25, rearUS);

	pause(0.2);
	deployKnocker();
	moveDistance(30, 10);
	moveDistance(100, 30);

}

task ohno() {
	while(true) {
		if(!everPressed && time1[T4] > 25000) {
			StopAllTasks();
		}
	}
}

int CenterGoal() {
	ClearTimer(T4);
	retractKnocker();
	turnUltra(0, 90);
	StartTask(raiseLift);
	moveDistanceRamp(40, 20);
	pause(1);
	int position = detectPosition();
	switch(position) {
		case 1:
			sound(1, 0.2);
			CenterPosition1();
			break;
		case 2:
			sound(2, 0.2);
			CenterPosition2();
			break;
		case 3:
			sound(3, 0.2);
			CenterPosition3();
			break;
		default:
			return -1;
	}

	deployClamp();
	while(!lifted);
	//int position = 2;
	readAllSwitches();
	//scoring commences
	bool anything_pressed = false;
	bool called_already = true;
	translateRTHeading(100, 90);
	while(!sideSwitch || !armSwitch) {
		readAllSwitches();
		if(tipSwitch) {
			translating = false;
			called_already = false;
			move(-20);
		}
		else if(sideSwitch) {
			translating = false;
			called_already = false;
			move(20);
		}
		else if(!called_already) {
			translateRTHeading(100, 90);
			called_already = true;
		}
		pause(0.2);
	}
	PlaySound(soundBeepBeep);
	scoreBall();
	move(0);
	translating = false;
	return position;
}

int selectInt(const string label, int prev) {
	int i = prev;
	while(nNxtButtonPressed != 3) {
		nxtDisplayCenteredTextLine(2, "%s: %d", label, i);
		if(nNxtButtonPressed == 1) i++;
		if(nNxtButtonPressed == 2) i--;
		if(nNxtButtonPressed != -1) wait1Msec(200);
		if(i<0) i = 0;
	}
	return i;
}

task main() {
	//servo[clamp2] = 127;
	//servo[clamp1] = 127;
	//servo[egRelease] = 127;
	//servo[egLift] = 127;
	int delay = selectInt("Delay", 0);
	ClearTimer(T4);
	resetArduino();
	while(time1[T4] < 5000) {
			writeDebugStreamLine("%d", time1[T4]);
			int time = round(5 - (time1[T4]/1000));
			nxtDisplayCenteredTextLine(2, "Reset IMU: %d sec left", time);
			wait10Msec(1);
	}

	nxtDisplayCenteredTextLine(2, "*****%ds******", delay);
	//createTeleopConfigFile(teleopFileName);
	waitForStart();
	pause(delay);

	int position = CenterGoal();
	CenterToKickstand(position);
}
